project_id: "2026-01-18__hectos"
client_name: "hectos"
created_at: "2026-01-18"
status: "active" # active, paused, completed, archived
current_stage: "70_experiment_analysis" # 10_research, 20_persona, ...
priority: "normal" # high, normal, low
owner: "" # PM/AM name
tags: []
